This Micronaut module specifies the Bill of Materials (BOM) for the Micronaut Project, also known as the Micronaut Platform.

The Micronaut Platform is a collection of modules that can be used to build Micronaut applications and have been verified to work well together.

It aggregates many of the individual Micronaut module BOMs and provides a single BOM to manage the versions of all the modules.

If you use either the https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/[Micronaut Gradle Plugin] or the https://micronaut-projects.github.io/micronaut-maven-plugin/latest/[Micronaut Maven Plugin], you do not need to add this module to your project because it will be added automatically.

NOTE: The Micronaut Platform BOM is available starting with Micronaut Framework 4, and replaces the Micronaut Framework 3 BOM published at `io.micronaut:micronaut-bom`. In Micronaut 4, both the Micronaut Platform BOM (`io.micronaut.platform:micronaut-platform`) and the Micronaut Core BOM (`io.micronaut:micronaut-core-bom`) are available.

== Using the Micronaut Platform BOM directly

If you are not using the Micronaut Gradle or Maven plugin, import the Micronaut Platform BOM in your build and omit versions for dependencies managed by the platform.

For Gradle, add the platform as a platform dependency:

[source,kotlin]
----
dependencies {
    implementation(platform("io.micronaut.platform:micronaut-platform:$micronautVersion"))
    implementation("io.micronaut.data:micronaut-data-jdbc")
}
----

For Maven, import the BOM in `dependencyManagement`:

[source,xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.micronaut.platform</groupId>
      <artifactId>micronaut-platform</artifactId>
      <version>${micronautVersion}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>io.micronaut.data</groupId>
    <artifactId>micronaut-data-jdbc</artifactId>
  </dependency>
</dependencies>
----

== The Micronaut Platform catalog

For Gradle users, the platform is also published as a https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog[version catalog] which can be used in your build scripts to add "blessed" dependencies to your project.

In order to use the version catalog, import it into your `settings.gradle(.kts)` file:

[source,kotlin]
----
val micronautVersion: String by settings // from gradle.properties
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        create("mn") {
            from("io.micronaut.platform:micronaut-platform:${micronautVersion}")
        }
    }
}
----

Then, you can use the catalog to add dependencies to your project:

[source,kotlin]
----
implementation(mn.micronaut.data.jdbc)
----
