This Micronaut module specifies the Bill of Materials (BOM) for the Micronaut Project, also known as the Micronaut Platform.

The Micronaut Platform is a collection of modules that can be used to build Micronaut applications and have been verified to work well together.

It aggregates many of the individual Micronaut module BOMs and provides a single BOM to manage the versions of all the modules.

If you use either the https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/[Micronaut Gradle Plugin] or the https://micronaut-projects.github.io/micronaut-maven-plugin/latest/[Micronaut Maven Plugin], you do not need to add this module to your project as it will be added automatically.

NOTE: Starting with Micronaut Platform 5.0, Kotlin applications built with Maven are not supported. Java applications built with Maven remain supported, and Kotlin applications built with Gradle remain supported.

NOTE: The Micronaut Platform BOM has existed since Micronaut Framework 4, and corresponds to the Micronaut Framework 3 BOM which was published at `io.micronaut:micronaut-bom`. In Micronaut 4, we provide both the Micronaut Platform BOM (`io.micronaut.platform:micronaut-platform`) and the Micronaut Core BOM (`io.micronaut:micronaut-core-bom`).

== Using the Micronaut Platform BOM

If your build does not use the Micronaut Gradle Plugin or the Micronaut Maven Plugin, import the Micronaut Platform BOM directly to manage Micronaut dependency versions.

For Gradle builds, add the platform dependency and then declare Micronaut dependencies without versions:

[source,kotlin]
----
val micronautVersion: String by project // from gradle.properties

dependencies {
    implementation(platform("io.micronaut.platform:micronaut-platform:$micronautVersion"))
    implementation("io.micronaut.data:micronaut-data-jdbc")
}
----

For Maven builds, import the platform BOM in `dependencyManagement` and then declare Micronaut dependencies without versions:

[source,xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.micronaut.platform</groupId>
      <artifactId>micronaut-platform</artifactId>
      <version>${micronaut.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>io.micronaut.data</groupId>
    <artifactId>micronaut-data-jdbc</artifactId>
  </dependency>
</dependencies>
----

The BOM manages dependency versions. It does not provide Gradle dependency aliases; use the Gradle version catalog when you want catalog aliases such as `mn.micronaut.data.jdbc`.

== The Micronaut Platform catalog

For Gradle users, the platform is also published as a https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog[version catalog] which can be used in your build scripts to add "blessed" dependencies to your project.

In order to use the version catalog, import it into your `settings.gradle(.kts)` file:

[source,kotlin]
----
val micronautVersion: String by settings // from gradle.properties
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        create("mn") {
            from("io.micronaut.platform:micronaut-platform:${micronautVersion}")
        }
    }
}
----

Then, you can use the catalog to add dependencies to your project:

[source,kotlin]
----
implementation(mn.micronaut.data.jdbc)
----
