package io.micronaut.platform.docs

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.tomlj.Toml
import org.w3c.dom.Element
import java.io.File
import javax.xml.XMLConstants
import javax.xml.parsers.DocumentBuilder
import javax.xml.parsers.DocumentBuilderFactory

abstract class GenerateManagedDependenciesGuide : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val rootCatalogFile: RegularFileProperty

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val generatedCatalogFile: RegularFileProperty

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val parentPomFile: RegularFileProperty

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val parentPomTemplateFile: RegularFileProperty

    @get:Input
    abstract val releaseVersion: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val rootCatalog = readCatalog(rootCatalogFile.get().asFile)
        val generatedCatalog = readCatalog(generatedCatalogFile.get().asFile)
        val parentPom = readParentPom(parentPomFile.get().asFile)
        val parentPomTemplate = parentPomTemplateFile.get().asFile.readText()

        val platformBoms = rootCatalog.libraries
            .filter { it.alias.startsWith("boms-") }
            .map { it.toGuideEntry("Platform BOM", it.alias) }

        val managedLibraries = rootCatalog.libraries
            .filter { it.alias.startsWith("managed-") }
            .map { it.toGuideEntry("Managed Library", it.alias) }

        val generatedCatalogEntries = (generatedCatalog.libraries + generatedCatalog.plugins)
            .map {
                it.toGuideEntry(
                    when {
                        it.plugin -> "Generated Catalog Plugin"
                        it.alias.startsWith("boms-") -> "Generated Catalog BOM"
                        else -> "Generated Catalog Library"
                    },
                    it.alias
                )
            }

        val parentEntries = parentEntries(rootCatalog, parentPom)

        validateSection("Platform BOMs", platformBoms)
        validateSection("Managed standalone libraries", managedLibraries)
        validateSection("Generated catalog coordinates", generatedCatalogEntries)
        validateSection("Parent POM plugin and property versions", parentEntries)
        validateParentTemplateProperties(parentPomTemplate, parentPom, parentEntries)

        val content = buildString {
            appendLine("// Generated by ${GenerateManagedDependenciesGuide::class.qualifiedName}. Do not edit.")
            appendLine()
            appendLine("This matrix is generated for Micronaut Platform ${ManagedDependenciesGuideSafety.escapeCell(releaseVersion.get())}.")
            appendLine()
            appendSection(
                "Platform BOMs",
                "Micronaut Platform imports these BOM coordinates into the generated platform metadata.",
                listOf("Alias", "Group ID", "Artifact ID", "Version", "Category"),
                platformBoms
            )
            appendSection(
                "Managed standalone libraries",
                "These standalone coordinates are managed directly by the platform catalog source.",
                listOf("Alias", "Group ID", "Artifact ID", "Version", "Category"),
                managedLibraries
            )
            appendSection(
                "Generated catalog coordinates",
                "These coordinates come from the generated Gradle version catalog artifact.",
                listOf("Alias", "Group ID", "Artifact ID / Plugin ID", "Version", "Category"),
                generatedCatalogEntries
            )
            appendSection(
                "Parent POM plugin and property versions",
                "These properties and plugin coordinates come from the generated parent POM and parent catalog metadata.",
                listOf("Property", "Alias", "Group ID", "Artifact ID", "Version", "Category"),
                parentEntries
            )
        }

        val anchors = anchorPattern.findAll(content).map { it.groupValues[1] }.toList()
        val duplicateAnchors = anchors.groupingBy { it }.eachCount().filterValues { it > 1 }.keys
        if (duplicateAnchors.isNotEmpty()) {
            throw GradleException("Managed dependencies guide has duplicate anchors: ${duplicateAnchors.sorted().joinToString()}")
        }

        outputFile.get().asFile.apply {
            parentFile.mkdirs()
            writeText(content)
        }
    }

    private fun parentEntries(rootCatalog: VersionCatalog, parentPom: ParentPom): List<GuideEntry> {
        val parentCatalogEntries = rootCatalog.libraries
            .filter { it.alias.startsWith("parent-") }
            .map { library ->
                val propertyName = parentPom.pluginVersionProperties[library.artifactId]
                    ?: "${library.alias.removePrefix("parent-")}.version"
                GuideEntry(
                    key = propertyName,
                    secondary = library.alias,
                    groupId = library.groupId,
                    artifactId = library.artifactId,
                    version = parentPom.properties[propertyName] ?: library.version,
                    category = if (library.artifactId.endsWith("-plugin")) "Parent POM Plugin" else "Parent POM Library"
                )
            }

        val documentedProperties = parentCatalogEntries.map { it.key }.toSet()
        val generatedParentProperties = parentPom.properties
            .filterKeys { it.endsWith(".version") && it !in documentedProperties }
            .map { (propertyName, version) ->
                GuideEntry(
                    key = propertyName,
                    secondary = "",
                    groupId = "",
                    artifactId = "",
                    version = version,
                    category = "Parent POM Property"
                )
            }

        return (parentCatalogEntries + generatedParentProperties)
            .sortedWith(compareBy<GuideEntry> { it.category }.thenBy { it.key }.thenBy { it.secondary })
    }

    private fun validateSection(name: String, entries: List<GuideEntry>) {
        if (entries.isEmpty()) {
            throw GradleException("Managed dependencies guide section '$name' has no entries")
        }
        val missingVersion = entries.filter { it.version.isBlank() }
        if (missingVersion.isNotEmpty()) {
            throw GradleException(
                "Managed dependencies guide section '$name' has entries without versions: " +
                    missingVersion.joinToString { it.key }
            )
        }
    }

    private fun validateParentTemplateProperties(template: String, parentPom: ParentPom, parentEntries: List<GuideEntry>) {
        val documentedProperties = parentEntries.map { it.key }.toSet()
        val pluginVersionProperties = parentPom.pluginVersionProperties.values.toSet()
        val missingProperties = propertyReferencePattern.findAll(template)
            .map { it.groupValues[1] }
            .filter { it in pluginVersionProperties }
            .filter { it !in parentPom.properties && it !in documentedProperties }
            .toSet()
        if (missingProperties.isNotEmpty()) {
            throw GradleException(
                "Parent POM template references version properties that are not generated or documented: " +
                    missingProperties.sorted().joinToString()
            )
        }
    }

    private fun StringBuilder.appendSection(
        title: String,
        description: String,
        headers: List<String>,
        entries: List<GuideEntry>
    ) {
        appendLine("== $title")
        appendLine()
        appendLine(description)
        appendLine()
        appendLine("|===")
        appendLine(headers.joinToString(" ") { "|$it" })
        entries.forEach { entry ->
            appendLine(entry.toRow(title))
        }
        appendLine("|===")
        appendLine()
    }

    private fun GuideEntry.toRow(sectionTitle: String): String {
        val anchor = "managed-dependencies-${slug(sectionTitle)}-${slug(category)}-${slug(key)}"
        return if (secondary.isEmpty() && groupId.isEmpty() && artifactId.isEmpty()) {
            "|[[$anchor]]${ManagedDependenciesGuideSafety.escapeCell(key)} | | | |${ManagedDependenciesGuideSafety.escapeCell(version)} |${ManagedDependenciesGuideSafety.escapeCell(category)}"
        } else if (secondary.isEmpty()) {
            "|[[$anchor]]${ManagedDependenciesGuideSafety.escapeCell(key)} |${ManagedDependenciesGuideSafety.escapeCell(groupId)} |${ManagedDependenciesGuideSafety.escapeCell(artifactId)} |${ManagedDependenciesGuideSafety.escapeCell(version)} |${ManagedDependenciesGuideSafety.escapeCell(category)}"
        } else {
            "|[[$anchor]]${ManagedDependenciesGuideSafety.escapeCell(key)} |${ManagedDependenciesGuideSafety.escapeCell(secondary)} |${ManagedDependenciesGuideSafety.escapeCell(groupId)} |${ManagedDependenciesGuideSafety.escapeCell(artifactId)} |${ManagedDependenciesGuideSafety.escapeCell(version)} |${ManagedDependenciesGuideSafety.escapeCell(category)}"
        }
    }

    private fun CatalogLibrary.toGuideEntry(category: String, key: String): GuideEntry =
        GuideEntry(
            key = key,
            secondary = "",
            groupId = groupId,
            artifactId = artifactId,
            version = version,
            category = category
        )

    private fun readCatalog(file: File): VersionCatalog {
        val result = Toml.parse(file.toPath())
        if (result.hasErrors()) {
            throw GradleException("Unable to parse $file: ${result.errors().joinToString()}")
        }

        val versionsTable = result.getTable("versions")
        val versions = versionsTable?.keySet()
            ?.associateWith { key -> versionsTable.getString(key) ?: "" }
            .orEmpty()

        val librariesTable = result.getTable("libraries")
            ?: throw GradleException("Version catalog $file does not contain a [libraries] table")

        val libraries = librariesTable.keySet().mapNotNull { alias ->
            val library = librariesTable.getTable(alias) ?: return@mapNotNull null
            val module: String? = library.getString("module")
            val moduleParts = module?.split(":", limit = 2).orEmpty()
            val groupId = library.getString("group") ?: moduleParts.getOrNull(0).orEmpty()
            val artifactId = library.getString("name") ?: moduleParts.getOrNull(1).orEmpty()
            val versionRef: String? = library.getTable("version")?.getString("ref")
            val version: String = versionRef?.let { versions[it] }
                ?: library.getString("version")
                ?: library.getTable("version")?.getString("require")
                ?: ""
            CatalogLibrary(alias, groupId, artifactId, version)
        }

        val pluginsTable = result.getTable("plugins")
        val plugins = pluginsTable?.keySet()
            ?.mapNotNull { alias ->
                val plugin = pluginsTable.getTable(alias) ?: return@mapNotNull null
                val versionRef: String? = plugin.getTable("version")?.getString("ref")
                val version: String = versionRef?.let { versions[it] }
                    ?: plugin.getString("version")
                    ?: plugin.getTable("version")?.getString("require")
                    ?: ""
                CatalogLibrary(alias, "", plugin.getString("id") ?: "", version, plugin = true)
            }
            .orEmpty()

        return VersionCatalog(versions, libraries.sortedBy { it.alias }, plugins.sortedBy { it.alias })
    }

    private fun readParentPom(file: File): ParentPom {
        val document = ManagedDependenciesGuideSafety.secureDocumentBuilderFactory()
            .newDocumentBuilder()
            .disableExternalEntities()
            .parse(file)

        val propertiesElement = document.getElementsByTagNameNS("*", "properties").item(0) as? Element
            ?: throw GradleException("Generated parent POM $file does not contain a properties section")
        val properties = propertiesElement.childElements()
            .associate { it.localName to it.textContent.trim() }

        val pluginVersionProperties = document.getElementsByTagNameNS("*", "plugin")
            .asElements()
            .mapNotNull { plugin ->
                val artifactId = plugin.childText("artifactId") ?: return@mapNotNull null
                val version = plugin.childText("version") ?: return@mapNotNull null
                val propertyName = propertyReferencePattern.matchEntire(version.trim())?.groupValues?.get(1)
                    ?: return@mapNotNull null
                artifactId to propertyName
            }
            .toMap()

        return ParentPom(properties, pluginVersionProperties)
    }

    private fun Element.childElements(): List<Element> =
        childNodes.asElements()

    private fun Element.childText(name: String): String? =
        childElements().firstOrNull { it.localName == name }?.textContent?.trim()

    private fun org.w3c.dom.NodeList.asElements(): List<Element> =
        (0 until length).mapNotNull { item(it) as? Element }

    private fun slug(value: String): String =
        value.lowercase()
            .replace(Regex("[^a-z0-9]+"), "-")
            .trim('-')

    private data class VersionCatalog(
        val versions: Map<String, String>,
        val libraries: List<CatalogLibrary>,
        val plugins: List<CatalogLibrary>
    )

    private data class CatalogLibrary(
        val alias: String,
        val groupId: String,
        val artifactId: String,
        val version: String,
        val plugin: Boolean = false
    )

    private data class ParentPom(
        val properties: Map<String, String>,
        val pluginVersionProperties: Map<String, String>
    )

    private data class GuideEntry(
        val key: String,
        val secondary: String,
        val groupId: String,
        val artifactId: String,
        val version: String,
        val category: String
    )

    companion object {
        private val anchorPattern = Regex("\\[\\[([^]]+)]]")
        private val propertyReferencePattern = Regex("\\$\\{([^}]+)}")
    }
}

internal object ManagedDependenciesGuideSafety {
    private val asciiDocMacroPattern = Regex("""(?i)\b(include|pass|link|image|xref|ifdef|ifndef|ifeval|endif)::?""")

    fun secureDocumentBuilderFactory(): DocumentBuilderFactory =
        DocumentBuilderFactory.newInstance().apply {
            isNamespaceAware = true
            setRequiredFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true)
            setRequiredFeature("http://apache.org/xml/features/disallow-doctype-decl", true)
            setRequiredFeature("http://xml.org/sax/features/external-general-entities", false)
            setRequiredFeature("http://xml.org/sax/features/external-parameter-entities", false)
            setRequiredFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false)
            setAttributeIfSupported(XMLConstants.ACCESS_EXTERNAL_DTD, "")
            setAttributeIfSupported(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "")
            isExpandEntityReferences = false
            try {
                isXIncludeAware = false
            } catch (_: UnsupportedOperationException) {
                // Some JAXP providers do not support XInclude; the external entity features above still apply.
            }
        }

    fun escapeCell(value: String): String =
        asciiDocMacroPattern.replace(
            value.replace("\n", " ")
                .replace("\r", " ")
                .replace("|", "\\|")
                .replace("<", "&#60;")
                .replace(">", "&#62;")
                .replace("[", "\\[")
                .replace("]", "\\]")
        ) { matchResult -> matchResult.value.replace(":", "&#58;") }

    private fun DocumentBuilderFactory.setRequiredFeature(name: String, value: Boolean) {
        try {
            setFeature(name, value)
        } catch (e: Exception) {
            throw GradleException("Unable to configure secure XML parser feature '$name'", e)
        }
    }

    private fun DocumentBuilderFactory.setAttributeIfSupported(name: String, value: String) {
        try {
            setAttribute(name, value)
        } catch (_: IllegalArgumentException) {
            // Older or alternate JAXP providers may not support these attributes.
        }
    }
}

private fun DocumentBuilder.disableExternalEntities(): DocumentBuilder =
    apply {
        setEntityResolver { _, _ ->
            throw GradleException("External XML entities are disabled for the managed dependencies guide generator")
        }
    }
